[FEAT/OPT] i18n on tags; transform tag path to English
UniiemStudio/CTFever pull request #48
Opened 2022-05-17 16:36 UTC by dextermallo

# Initiates

I am a rookie for CTF and just found this fantastic tool recently, hope I can contribute a bit :)
(P.S. I only learned Vue a little around 3 years ago, please do let me know if there's anything I can improve)

# Changes

## Optimization
1. Support i18n on function `tags`: It would be great if all the text displayed the exact language people choose :). Noted that it only supports those tools with `displayed: true`.

## Feature
2. Transform the tag path to English-only: When clicking on the tag (`https://ctfever.uniiem.com/tag/<tagType>`) it will display with encoded one right now (eg. https://ctfever.uniiem.com/tag/%E5%AD%97%E7%AC%A6%E7%BC%96%E7%A0%81). It would be prettier when using English-only just like the other url.

## Chore
3. Tag changes: Since there's new support for i18n on tags, as a person who just joins into the CTF recently, please kindly help to correct my poor translation if needed :)

| Code                    | English                   | Chinese  |
|-------------------------|---------------------------|----------|
| encodingAndDecoding     | Encoding And Decoding     | 字符编码 |
| generator               | Generator                 | 产生器   |
| hash                    | Hash                      | 杂凑     |
| encryptionAndDecryption | Encryption And Decryption | 加密算法 |
| conversion              | Conversion                | 数据处理 |
| disassembler            | Disassembler              | 反编译   |
| obfuscation             | Obfuscation               | 混淆     |
| complier                | Complier                  | 编译器   |
| utility                 | Utility                   | 调试工具 |
| inspection              | Inspection                | 校验     |

I also did some changes to some of the tools, here's the list:
| Tool name     | Before         | After    |
|---------------|----------------|----------|
| uuid          | 信息摘要       | 产生器   |
| messageDigest | 信息摘要       | 杂凑     |
| ipAttribution | IP2Geo         | 数据处理 |
| crc           | 信息摘要, 校验 | 校验     |

# Tests

`node version: v12.22.1`

- [x] On-prem run `yarn dev`
- [x] On-prem run `yarn build`
- [x] Functionality of Changes 1
- [x] Functionality of Changes 2
- [x] Functionality of Changes 3 

![Screen Shot 2022-05-18 at 00 02 42](https://user-images.githubusercontent.com/29012607/168862553-94f166e4-0c74-472b-8982-3253b8cd4fe3.png)

![Screen Shot 2022-05-18 at 00 02 49](https://user-images.githubusercontent.com/29012607/168862565-3d9947e7-dfbe-4ddc-adbd-13b4022537a0.png)

![Screen Shot 2022-05-18 at 00 02 54](https://user-images.githubusercontent.com/29012607/168862569-f4302e89-1dfc-4b99-ad90-a181f12405f2.png)

![Screen Shot 2022-05-18 at 00 03 11](https://user-images.githubusercontent.com/29012607/168862579-9f8283aa-8798-4a42-b25d-fb5b6efabfcb.png)

![Screen Shot 2022-05-18 at 00 02 31](https://user-images.githubusercontent.com/29012607/168862541-08476a71-2fcc-4c32-ade1-bc85ac154379.png)

Thanks again for the amazing tool :)

2022-05-17 17:32 UTC, HoshinoSuzumi requested changes
Review has been completed, please check.
Thank you very much for your contribution and support 😉

2022-05-17 17:32 UTC, HoshinoSuzumi commented on lang/en-US.js
> +    disassembler: 'Disassembler',
“反编译” 而不是 “反汇编”
'Decompiler' instead of 'Disassembler'

2022-05-17 23:08 UTC, dextermallo commented on lang/zh-CN.js
> +    inspection: '校验'
Fixed in [fb9932b](https://github.com/UniiemStudio/CTFever/pull/48/commits/fb9932b734414725da095b649d31028721df93dd)

2022-05-17 23:09 UTC, dextermallo commented on lang/zh-CN.js
> +    disassembler: '反编译',
Fixed in [fb9932b](https://github.com/UniiemStudio/CTFever/pull/48/commits/fb9932b734414725da095b649d31028721df93dd)

2022-05-17 23:09 UTC, dextermallo commented on lang/en-US.js
> +    inspection: 'Inspection'
Fixed in [fb9932b](https://github.com/UniiemStudio/CTFever/pull/48/commits/fb9932b734414725da095b649d31028721df93dd)

2022-05-17 23:09 UTC, dextermallo commented on lang/en-US.js
> +    disassembler: 'Disassembler',
Fixed in [fb9932b](https://github.com/UniiemStudio/CTFever/pull/48/commits/fb9932b734414725da095b649d31028721df93dd)

2022-05-18 02:47 UTC, HoshinoSuzumi approved these changes
Thanks a lot for your contribution again! Have a nice day

2022-05-18 02:49 UTC, merged