[Feat] Docker 容器支持
UniiemStudio/CTFever pull request #59
Opened 2022-06-11 12:13 UTC by lixworth

* [x] 编写 Dockerfile 
* [x]  编写 build ci 
* [ ] 发布镜像到精选到 dockerhub
* [ ] 修改 readme.md

2022-06-12 13:38 UTC, HoshinoSuzumi commented
👍

2022-06-14 10:49 UTC, HoshinoSuzumi commented
🥇

2022-07-04 16:24 UTC, HoshinoSuzumi commented
咕咕咕

2022-09-07 05:00 UTC, HoshinoSuzumi commented
🕊️

2022-09-11 17:45 UTC, lixworth commented
快了快了

2022-12-17 21:53 UTC, lixworth commented
![image](https://user-images.githubusercontent.com/22554300/208267279-6799082e-ca3d-44b5-bccd-2c1ae6514288.png)

2022-12-17 22:02 UTC, lixworth commented
发布容器镜像过程 计划使用 github action 进行，请将用户凭据存储在项目 secret 中。 @HoshinoSuzumi

2022-12-27 04:44 UTC, HoshinoSuzumi requested changes
nginx需要伪静态规则

2023-02-27 02:23 UTC, HoshinoSuzumi approved these changes

2023-02-27 02:24 UTC, merged